[WIP] Add text extraction notebook and other demo2 files
os-climate/aicoe-osc-demo pull request #27
Opened 2021-09-29 21:18 UTC by Shreyanand

For issue #11 and issue #26, add files required to run text extraction phase of demo 2.

2021-09-30 20:29 UTC, erikerlandson commented
@Shreyanand  lgtm

2021-10-01 18:35 UTC, MichaelClifford commented
>Questions that remain to be addressed:

>What would be the best way to give credit to the Allianz NLP repository?
The dataset currently is in the data folder of the repo, do we want to bring s3 in the picture at this point?

@Shreyanand do these need to be addressed in this PR? or should they be turned into additional issues?

2021-10-01 18:57 UTC, MichaelClifford commented
> The dataset currently is in the data folder of the repo, do we want to bring s3 in the picture at this point?

@Shreyanand, I am generally not a fan of using github as the place to store data (other than small example sets). This data is not huge, but I think it might be a good idea to put this data in remote storage and interactive with it that way. WDYT? 

@MichaelTiemannOSC is it all right to move this data and make it available through remote storage?

2021-10-01 19:12 UTC, MichaelTiemannOSC commented
The Data Commons is designed around the concept of having access to cloud storage for just such a reason.  We should create a folder for this.  We just need to figure out an appropriate name for the folder that we can live with for a while.

2021-10-01 19:24 UTC, MichaelClifford commented
@MichaelTiemannOSC great : ) 

Is this something that merits a new issue in the os_c_data_commons repo to discuss?

2021-10-01 19:46 UTC, erikerlandson commented
@MichaelClifford  the following would be a good place to discuss:
https://github.com/os-climate/os_c_data_commons/issues/68

2021-10-07 19:31 UTC, MichaelClifford commented
@MichaelTiemannOSC  According to the linked issue it seems like the ESG corporate data we are looking to use here is still a bit of an outlier. I'm happy with any naming convention/bucket location folks want to use, but would `corpdata/ESG/**`      in the 'ocp-odh-os-demo-s3' bucket suffice for now?

Let me know what you think :smile:

2021-10-11 14:15 UTC, chauhankaranraj requested changes
Just small nits otherwise /lgtm

2021-10-11 14:15 UTC, chauhankaranraj commented on notebooks/demo2/pdf_text_extraction.ipynb
> +    "    sys.path.insert(1, src_path)\n",
If `src` is already added to Pipfile, do we still need to add it to path?

2021-10-11 14:15 UTC, chauhankaranraj commented on src/__init__.py
> -"""Analytics compiled into python code."""
Would precommit complain if we remove this?

2021-10-11 16:22 UTC, chauhankaranraj commented
> @Shreyanand do these need to be addressed in this PR? or should they be turned into additional issues?

Agreed, let's discuss this in a separate issue - #39 - and unblock this PR :)

2021-10-11 17:17 UTC, MichaelClifford commented
/lgtm

2021-10-11 17:51 UTC, chauhankaranraj approved these changes
changes look good, thanks :smile:

2021-10-11 17:52 UTC, merged